### ISSUE TITLE
Link to document index on main page

### ISSUE THREAD

**Issue by hassanfarid** [awsdocs/aws-lambda-developer-guide#10]
We should should create [index](../tree/master/doc_source/index.md) on [README](../tree/master/README.md) file.

**Comment by roryj** [comment]
Hey @hassanfarid, I am not sure what you mean by this comment? Do you mean put a link to the README file in the index? If so, the README file is very specific to the github repo, whereas the index file is the actual index page of the website

**Comment by hassanfarid** [comment]
I meant the other thing. Put the link on README file. This is the default file that is displayed to everyone on this repository.it should link to actual file, or else people will have to find it themselves.

Does this make sense?

**Comment by hassanfarid** [comment]
@roryj  I made an edit, and have submitted PR. Let me know, if this is helpful.
