### ISSUE TITLE
error code wrong?

### ISSUE THREAD

**Issue by lmunro** [awsdocs/aws-lambda-developer-guide#127]
[retries-on-errors.md](aws-lambda-developer-guide/doc_source/retries-on-errors.md)

says 

> The status code is 200 for function errors

Should that be 500?

**Comment by mwunderl** [comment]
Hi Lachlan, Lambda returns 200 if it was able to invoke the function. If the function returns an error, that's reflected in the `X-Amz-Function-Error` header, but the status code is still 200.
