### ISSUE TITLE
Lambda running in default VPC

### ISSUE THREAD

**Issue by madhuri1596** [awsdocs/aws-lambda-developer-guide#133]
I saw in doc: https://docs.aws.amazon.com/lambda/latest/dg/configuration-vpc.html that by default Lambda runs in a secure VPC with access to AWS services and the internet. But when ever we create a new lambda it shows no VPC under configuration tab and header network.

**Comment by sime** [comment]
I believe in this case the default VPC in the Lambda UI is implied.
