### ISSUE TITLE
Python 3.7 is missing PYTHONPATH

### ISSUE THREAD

**Issue by mohdlee** [awsdocs/aws-lambda-developer-guide#135]
We recently discovered that in the python3.7 runtime, `PYTHONPATH` is missing. Not sure if this is a gap in the doc or a bug on the lambda side. Anyone has any idea?

**Comment by mwunderl** [comment]
I've confirmed that this was intentionally removed for new Python runtimes and updated the topic accordingly-
https://docs.aws.amazon.com/lambda/latest/dg/lambda-environment-variables.html

Thanks,
-Michael
