### ISSUE TITLE
Document that certain APIs don't work across accounts

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/aws-lambda-developer-guide#139]
The [documentation]() says this:

> You can grant cross-account access for **any API action that operates on an existing function**. For example, you could grant access to lambda:ListAliases to let an account get a list of aliases, or lambda:GetFunction to let them download your function code. Add each permission separately, or use lambda:* to grant access to all actions for the specified function.

That would suggest that all actions on [this page](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awslambda.html) that operate on the `function` resource, except for `CreateFunction`, can work across accounts.

From my testing, in practice that list appears to be more restrictive. `AddPermission`, `DeletePermission`, and `UpdateFunctionConfiguration` at least also don't seem to allow me to use them across accounts.

**Comment by mwunderl** [comment]
Hi Daniel,

Thanks for pointing this out. I'll confirm the set of API operations that are supported and update the topic.

**Comment by mwunderl** [comment]
Added here-
https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html#permissions-resource-xaccountinvoke

**Comment by copumpkin** [comment]
Actually, I still see `UpdateFunctionConfiguration` on that list, which didn't work when I tested it.

**Comment by copumpkin** [comment]
Also, you have `PutFunctionConcurrency` on the list twice when I think the second one was meant to be `DeleteFunctionConcurrency`.

**Comment by copumpkin** [comment]
From my testing, `TagResource` and `UntagResource` and `UpdateFunctionCode` also work.

**Comment by mwunderl** [comment]
Thanks for the review and sorry the errors. I'll clean it up.

**Comment by mwunderl** [comment]
fixed in [9d908ef](https://github.com/awsdocs/aws-lambda-developer-guide/commit/9d908efb30ba7d406c2dd55f10c8dd1b4f1eef20)
