### ISSUE TITLE
Lambda Consumer with KPL Producer needs more explanation

### ISSUE THREAD

**Issue by ashleyfrieze** [awsdocs/aws-lambda-developer-guide#140]
I followed the guide here - https://github.com/awsdocs/aws-lambda-developer-guide/blob/master/doc_source/with-kinesis-create-package.md - for making a function to process messages from a Kinesis stream.

This worked fine for messages that were produced individually, but when several messages were produced in a short time-frame, the latter messages were prefixed by extra characters, including the partitionKey and some pipe characters.

After some research, I realised that I needed to either disable the Kinesis Aggregation using the producer library (which I chose) or I needed to use https://github.com/awslabs/kinesis-aggregation

It would be enormously helpful if there were some warnings in the documentation about creating a Kinesis function on the subject of aggregation.

**Comment by mwunderl** [comment]
Hi,

Thanks for the detailed report! I'll add a note about aggregation for now, and look into providing sample code that uses the aggregation library.

We've also recently added a Kinesis-based sample application that may be of interest-
https://github.com/awsdocs/aws-lambda-developer-guide/tree/master/sample-apps/list-manager

Thanks,
-Michael at AWS

**Comment by mwunderl** [comment]
Added a note here-
https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis-create-package.html
