### ISSUE TITLE
Node.js 8.xx update deprecation clarification

### ISSUE THREAD

**Issue by tim-pugh** [awsdocs/aws-lambda-developer-guide#153]
I believe it's possible to at least update a node.js 8.xx RUNTIME past it's update deprecation date.

So customers won't need to re-create a new lambda, just simply go in and update the runtime.

**Comment by mwunderl** [comment]
I'll confirm with the engineering team.
Thanks,

**Comment by mwunderl** [comment]
Yes. You can update a function with a deprecated runtime as long as you change the runtime to one that's supported. You just won't be able to change it back later.
