### ISSUE TITLE
Warning when using the policy with wildcard in Resource

### ISSUE THREAD

**Issue by milevmartin** [awsdocs/aws-lambda-developer-guide#160]
Dear Colleagues,

when I use the following policy for example:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublishLayers",
            "Effect": "Allow",
            "Action": [
                "lambda:PublishLayerVersion"
            ],
            "Resource": "arn:aws:lambda:*:*:layer:test-*"
        },
        {
            "Sid": "ManageLayerVersions",
            "Effect": "Allow",
            "Action": [
                "lambda:GetLayerVersion",
                "lambda:DeleteLayerVersion"
            ],
            "Resource": "arn:aws:lambda:*:*:layer:test-*:*"
        }
    ]
}

copied from the article - 
https://docs.aws.amazon.com/lambda/latest/dg/access-control-identity-based.html

I receive a warning in AWS Console:

"This policy defines some actions, resources, or conditions that do not provide permissions. To grant access, policies must have an action that has an applicable resource or condition. For details, choose Show remaining Learn more"

When I inspect the warning i can see:

GetLayerVersion(No access)
This action does not have an applicable resource.

DeleteLayerVersion(No access)
This action does not have an applicable resource.

PublishLayerVersion(No access)
This action does not have an applicable resource.

where we can clearly see that we have a Resource specified;

When I place a Resource name that does not contains * the warning Disappears;

**Comment by mwunderl** [comment]
Hi, yes the IAM console does show a warning when you use wildcards. The policy is still valid.
