### ISSUE TITLE
Does the `nodejs12.x` runtime include full-icu?

### ISSUE THREAD

**Issue by styfle** [awsdocs/aws-lambda-developer-guide#183]
I don't see this documented anywhere, but a quick test makes me think that AWS Lambda is using a custom build of Node.js with full icu.

```js
console.log(new Intl.DateTimeFormat('en-GB').format(new Date('2015-05-30')));
// prints the expected "30/05/2015"
```

Can this feature be relied upon?

Node.js Docs: https://nodejs.org/docs/latest-v12.x/api/intl.html#intl_embed_the_entire_icu_full_icu
AWS Lambda Docs: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by devlinbd2** [comment]
If it is an un-advertised feature, it could be removed from a future version without warning. The Node.js docs suggest ways for testing that the package is present, such as:
const hasICU = typeof process.versions.icu === 'string';

If the package is not present, you could create it as a layer for any function that needs it.

**Comment by styfle** [comment]
> If the package is not present, you could create it as a layer for any function that needs it.

@devlinbd2 As far as I know, a Lambda can't add a Layer to itself, so this solution is not sufficient.

I think a better solution is documenting your build process for Node.js and other runtimes. Which flags were used, etc?

This was almost achieved in the `aws/aws-lambda-base-images` repo.

However, that repo is more of a dump than it is a build recipe as seen in issue https://github.com/aws/aws-lambda-base-images/issues/7.

**Comment by devlinbd2** [comment]
Looks like the Lambda team is looking at the issue for container images, but I am not sure about the runtimes. I will pass along your request to the PM team.
