### ISSUE TITLE
Upload multiple functions

### ISSUE THREAD

**Issue by jigar288** [awsdocs/aws-lambda-developer-guide#184]
How would I deploy multiple functions using cloudformation? I tried changing the name of the function but it just updated the old lambda function instead of creating a new one

**Comment by mwunderl** [comment]
Hi Jigar,

See the following sample apps that create multiple functions in a single template:
[list-manager](https://github.com/awsdocs/aws-lambda-developer-guide/tree/master/sample-apps/list-manager)
[error-processor](https://github.com/awsdocs/aws-lambda-developer-guide/tree/master/sample-apps/error-processor)

Thanks,
-Michael
