### ISSUE TITLE
Runtime OS references out of date?

### ISSUE THREAD

**Issue by athewsey** [awsdocs/aws-lambda-developer-guide#185]
Printing `os.uname()` in a new Python 3.6 Lambda function in `ap-southeast-1` today, I got output of:

```
os.uname(): posix.uname_result(sysname='Linux', nodename='169.254.252.45', release='4.14.165-102.205.amzn2.x86_64', version='#1 SMP Fri Feb 14 22:46:57 UTC 2020', machine='x86_64')
```

As I understood the `amzn2` in the release meant it's an AL2 system right? Not AL1 as documented on the Lambda Runtimes page

**Comment by heitorlessa** [comment]
Which runtime did you use Alex?

**Comment by mwunderl** [comment]
`os.uname` shows the operating system of the underlying host. The function runs in an Amazon Linux (v1) execution environment on an AL2 host. The system packages available to the function will be those on Amazon Linux (v1).

**Comment by athewsey** [comment]
Ah thanks @mwunderl I guess that clears it up... Out of interest, do you know an alternative check from Python that would work as intended on Lambda?

**Comment by mwunderl** [comment]
I'm not aware of one no. I'll check with the engineering team.

**Comment by devlinbd2** [comment]
Original question has been answered.
