### ISSUE TITLE
Question about the `blank-nodejs` example

### ISSUE THREAD

**Issue by coreysnyder04** [awsdocs/aws-lambda-developer-guide#187]
In your `blank-nodejs` example, you create an S3 bucket for `deployment artifacts` but some things aren't clear. 

1. I can't find anywhere in the code you're actually writing to that bucket. Where does this happen?
2. What are the build artifacts for? What would be the result if I removed the bucket? 

Maybe the documentation could be updated to make this more clear.

**Comment by mwunderl** [comment]
Hi Corey,

When you run the deploy script, the `aws cloudformation package` command uploads the function code to the artifact bucket and creates a new version of the application template that references the artifacts in Amazon S3. CloudFormation needs the artifacts in Amazon S3 for the deployment step, but they are not required after that and are safe to delete.

Thanks,
-Michael
