### ISSUE TITLE
[Question] What about the layers

### ISSUE THREAD

**Issue by godrose** [awsdocs/aws-lambda-developer-guide#200]
The template file references lib folder which is absent from the code. 
So what is going on with the layers here?

**Comment by wynged** [comment]
:+1: looks like the `packages` folder is missing in the blank-python example

**Comment by mwunderl** [comment]
These examples include a script that downloads dependencies and stages them in the layer folder-
https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/blank-nodejs/2-build-layer.sh
https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/blank-python/2-build-layer.sh
