### ISSUE TITLE
issue with blank-java

### ISSUE THREAD

**Issue by chenkaijiekidd** [awsdocs/aws-lambda-developer-guide#201]
there is no policy name 'AWSXrayWriteOnlyAccess' so that run deply.sh will be failed

**Comment by ankurongit** [comment]
Hey @chenkaijiekidd ,the _'AWSXrayWriteOnlyAccess'_ policy is present in the [template.yml](https://github.com/awsdocs/aws-lambda-developer-guide/blob/a37c20923f57528f4521a323c69a1a29ab79cbb0/sample-apps/blank-java/template.yml#L18).
Please help me with the details, to understand the problem you're facing.
