### ISSUE TITLE
Go runtime on Amazon Linux 2 is not documented

### ISSUE THREAD

**Issue by shogo82148** [awsdocs/aws-lambda-developer-guide#215]
Hi,
Recently, Go runtime on Amazon Linux 2 is announced.
https://aws.amazon.com/about-aws/whats-new/2020/08/aws-lambda-supports-go-amazon-linux-2/

But, I can't find Amazon Linux 2 in the Go runtimes section.

https://github.com/awsdocs/aws-lambda-developer-guide/blame/0168ba0ea389592df2e41f9666850c4fa79ac6f1/doc_source/lambda-golang.md#L8-L10

The announce says that select `provided.al2` ("provide your own bootstrap on Amazon Linux 2 runtime") to use Go runtime on Amazon Linux 2, but the example of deployment package still uses the `go1.x` runtime that is on Amazon Linux.

https://github.com/awsdocs/aws-lambda-developer-guide/blame/main/doc_source/golang-package.md#L21-L26

Where can I found the documents about Go runtime on Amazon Linux 2?

**Comment by devlinbd2** [comment]
We do not have these instructions in the documentation yet, but there is a blog post that shows how to build Go functions on provided.al2 using SAM:
https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-to-al2/
