### ISSUE TITLE
Wrong steps in Pipeline Creation

### ISSUE THREAD

**Issue by renetalk** [awsdocs/aws-lambda-developer-guide#22]
The step 4 in https://github.com/awsdocs/aws-lambda-developer-guide/blob/master/doc_source/build-pipeline.md seems to be wrong.
The point 2. should show another icon. The pencil is wrong and should be a "+" sign. What you really want to do in this step is to add another action and not edit the existing one. This is not clear in the current version.

**Comment by spaethp** [comment]
Thanks for the feedback.
