### ISSUE TITLE
nodejs14.x ?

### ISSUE THREAD

**Issue by chiefbiiko** [awsdocs/aws-lambda-developer-guide#221]
according to [https://nodejs.org/en/about/releases/](https://nodejs.org/en/about/releases/)...

<img width="489" alt="node_lts" src="https://user-images.githubusercontent.com/22937570/98907530-dfa96300-24b6-11eb-9d43-7dfba287b3ed.PNG">

...node v14 just got active lts last month and v12 will be moving into maintenance soon

is there a release date for a `nodejs14.x` lambda runtime?

**Comment by devlinbd2** [comment]
Lambda periodically updates the list of available runtimes, but generally does not announce future release dates.
