### ISSUE TITLE
Go Runtime does not support extension API

### ISSUE THREAD

**Issue by trosenblatt-norberthealth** [awsdocs/aws-lambda-developer-guide#224]
I saw the release of AppConfig, and jumped on it to use it on my go lambdas to replace my environment variables.
I followed the tutorial on https://docs.aws.amazon.com/appconfig/latest/userguide/appconfig-integration-lambda-extensions.html.
I pushed my Go lambda with the new layer, just to realise that my AppConfig extension was never called ... ( I tested with python it works great)

Then I read the list of supported runtime, and go seems to be not included.

It seems that all language are supported even CustomRuntime, so I don't get why go is not supported.
Would it mean I have to run my go lambda on a CustomRuntime (provided.al2)?

Also if you can share why go is left alone, that would be great !

Thks a lot,
Thomas.

**Comment by devlinbd2** [comment]
This is a documentation forum, so I do not have an answer about why Extensions are not supported on the Go runtime. You may get an answer if you post your question on the Lambda forum: https://forums.aws.amazon.com/forum.jspa?forumID=186
