### ISSUE TITLE
Update all references to `master` branch to `main`

### ISSUE THREAD

**Issue by chefren** [awsdocs/aws-lambda-developer-guide#227]
The `README.md` file has been updated but many other files still refer to the `master` branch, eg: [`CONTRIBUTING.md`](https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/CONTRIBUTING.md)

**Comment by devlinbd2** [comment]
I have replaced as many references as possible. There are some references to other services and other github repos that still use the word `master`.
