### ISSUE TITLE
dynamodb:ListShard permission is missing from the lambda Execution Role

### ISSUE THREAD

**Issue by dvedhire** [awsdocs/aws-lambda-developer-guide#237]
**Request:**
Update the permissions required on the lambda execution role in the documentaion  [here](https://github.com/awsdocs/aws-lambda-developer-guide/blob/ec610ccf4760ff4c753c99b74240e0f79b4c6aef/doc_source/with-ddb.md#user-content-events-dynamodb-permissions) to include dynamodb:ListShards action. 

**Issue:** 

Currently, the [documentation](https://github.com/awsdocs/aws-lambda-developer-guide/blob/ec610ccf4760ff4c753c99b74240e0f79b4c6aef/doc_source/with-ddb.md#user-content-events-dynamodb-permissions) related to lambda Execution Role Permissions to manage resources related to DynamoDB streams stream mentions the following permissions:

dynamodb:DescribeStream
dynamodb:GetRecords
dynamodb:GetShardIterator
dynamodb:ListStreams

However, when using these permissions itself, the creation of `AWS::Lambda::EventSourceMapping` resource is failing with the following error: `Invalid request provided: Cannot access stream <Stream ARN>. Please ensure the role can perform the GetRecords, GetShardIterator, DescribeStream, ListShards, and ListStreams Actions on your stream in IAM. (Service: Lambda, Status Code: 400)`

From the above error message, it is clear that the `dynamodb:ListShards` permission is also required to create `EventSourceMapping` resource. Providing this permission on the lambda execution role has fixed the error.

I would request to update the documentation to include the `dynamodb:ListShards` permission in order to avoid confusion.

**Comment by devlinbd2** [comment]
Thank you for providing the feedback. I have updated the permissions list to include dynamodb:ListShards.
