### ISSUE TITLE
gettingstarted-limits.md out of date

### ISSUE THREAD

**Issue by RossWilliams** [awsdocs/aws-lambda-developer-guide#242]
https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html has recent changes which are not in this repository.

Specifically, there is a new reduced limit for per-file size console editor files on the webpage:

```text
"Deployment package (.zip file archive) size" - "3 MB (console editor), 512 KB maximum for an individual file".
```

In this repo the line reads:

```text
"Deployment package (.zip file archive) size" - "3 MB (console editor)"
```

**Comment by devlinbd2** [comment]
The web pages reflect the definitive published content. Unfortunately, publishing to GitHub is a manual process. We will try to make sure that we perform the publishing task once a week.
