### ISSUE TITLE
Redundant call to toString()

### ISSUE THREAD

**Issue by swpalmer** [awsdocs/aws-lambda-developer-guide#247]
String concatenation will call toString() for you.  Explicitly calling it here is superfluous.

https://github.com/awsdocs/aws-lambda-developer-guide/blob/b6cd7d3c9f48411f6892f6d03c1b4186d60c55fa/sample-apps/java-events/src/main/java/example/Util.java#L18

**Comment by devlinbd2** [comment]
Thank you for filing the issue. I have corrected the code.
