### ISSUE TITLE
Invocation Payload Size error

### ISSUE THREAD

**Issue by anubhav1** [awsdocs/aws-lambda-developer-guide#252]
I am running a webserver on greengrass like [this](https://iot-greengrass-1dotx.workshop.aws/advanced-module/running-a-webserver-inside-greengrass.html). When I am sending a json object from my IoT thing to this server, I get an error of exceeding msg size limit of 128KB. How to send a json object above 128KB from IoT thing to server running on greengrass core?

**Comment by devlinbd2** [comment]
That seems like a large payload for an IoT application. Have you tried asking your question on the IoT product forum? This is not a documentation issue.
