### ISSUE TITLE
blank-python sample app error on step 3

### ISSUE THREAD

**Issue by workloadmike** [awsdocs/aws-lambda-developer-guide#263]
When I get to step 3 of the blank-python sample app it gives an error.

_$ ./3-deploy.sh_
Successfully packaged artifacts and wrote output template to file out.yml.
**An error occurred (MissingAuthenticationToken) when calling the DescribeStacks operation: Request is missing Authentication Token**

It is related to this line of code:
`aws cloudformation deploy --template-file out.yml --stack-name blank-python --capabilities CAPABILITY_NAMED_IAM`

This is the sample app I am trying to run:
[https://github.com/awsdocs/aws-lambda-developer-guide/tree/main/sample-apps/blank-python](https://github.com/awsdocs/aws-lambda-developer-guide/tree/main/sample-apps/blank-python)

I tried searching for information on this error but it is not easy to find any details as to why this is happening and how to fix it myself.

Thanks!!

**Comment by devlinbd2** [comment]
Make sure you have configured your credentials in AWS CLI:
https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html
