### ISSUE TITLE
            "Resource": "arn:aws:iam::aws:policy/*"  is invalid declaration

### ISSUE THREAD

**Issue by StanSilas** [awsdocs/aws-lambda-developer-guide#266]
https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/doc_source/access-control-identity-based.md 

```
     {
            "Sid": "ViewExecutionRolePolicies",
            "Effect": "Allow", 
            "Action": [
                "iam:GetPolicy",
                "iam:GetPolicyVersion"
            ],
            "Resource": "arn:aws:iam::aws:policy/*"
        },
```

If I use this it says unrecognized resource

Is there a way to use this?

**Comment by devlinbd2** [comment]
Thank you for raising the issue. I updated the resource name: 
"Resource": "arn:aws:iam::accountNumber:policy/*"
