### ISSUE TITLE
When I am sending the files object as byte to lambda invoke function its not working

### ISSUE THREAD

**Issue by itsmano** [awsdocs/aws-lambda-developer-guide#271]
Getting this below error
botocore.errorfactory.InvalidRequestContentException: An error occurred (InvalidRequestContentException) when calling the Invoke operation: Could not parse request body into json: Could not parse payload into json: Unrecognized token 'm': was expecting ('true', 'false' or 'null')
 at [Source: (byte[])"m"; line: 1, column: 3]

Does it say that only the JSON payload lambda invoke function will accept? if i want to send the file object to lambda then how can we do that?

**Comment by devlinbd2** [comment]
JSON payload for the function handler is documented here:
https://docs.aws.amazon.com/lambda/latest/dg/python-handler.html
To pass a file object to your function, you can add the file to S3 and read the file from the Lambda function. This tutorial shows an example:
https://docs.aws.amazon.com/lambda/latest/dg/with-s3-example.html
