### ISSUE TITLE
Wildcard "SourceArn" to represent all "execute-api" s for a particular account

### ISSUE THREAD

**Issue by charlie9526** [awsdocs/aws-lambda-developer-guide#279]
What I want is to restrict lambda access to API gateways of a known account. I tried that adding following block to the lambda policies. Am I correct? 
 
Conditions:
{
 "ArnLike": {
  "AWS:SourceArn": "arn:aws:execute-api: 'lambda-region':'account-id':*"
 }
}

**Comment by mwunderl** [comment]
Is this question related to content in the developer guide, or sample code in this repo?
