### ISSUE TITLE
Clarification on ECR Policy Permissions

### ISSUE THREAD

**Issue by rmorris-chime** [awsdocs/aws-lambda-developer-guide#286]
https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/doc_source/configuration-images.md#update-the-user-permissions

1. Are these permissions needed for the principal that will be creating the function if the ECR repo already has a policy statement that will allow the Lambda service principal to retrieve the image?
2. Is the `ecr:InitiateLayerUpload` permission needed because a new, Lambda optimized image is pushed to the customer ECR repo after a function is created with it? If not, why is that permission needed?

**Comment by devlinbd2** [comment]
Thank you for posting these questions. This section of the document was not correct. You do not add permissions to the 
principal that will be creating the function, and ecr:InitiateLayerUpload permission is not required. 

I have updated the web documentation, and will refresh the Github version soon. There are currently 2 scenarios:
a. You can add ecr:BatchGetImage and ecr:GetDownloadUrlForLayer for principal lambda.amazonaws.com in the repository’s resource policy.
b. If the calling Principal has ecr:getRepositoryPolicy and ecr:setRepositoryPolicy,  Lambda will automatically create a Repo policy or update the Repo policy to include ecr:BatchGetImage and ecr:GetDownloadUrlForLayer.

Details are here:
https://docs.aws.amazon.com/lambda/latest/dg/configuration-images.html#configuration-images-permissions
