### ISSUE TITLE
Clarification on cross account image for lambda

### ISSUE THREAD

**Issue by clippered** [awsdocs/aws-lambda-developer-guide#289]
https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/doc_source/lambda-images.md

Currently, creating a lambda function from the console using an image from a private ECR repository in another AWS account says the image is invalid. The host ECR repo has
```{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "AllowPull",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::XXX:root"
      },
      "Action": [
        "ecr:BatchCheckLayerAvailability",
        "ecr:BatchGetImage",
        "ecr:DescribeImages",
        "ecr:DescribeRepositories",
        "ecr:GetDownloadUrlForLayer"
      ]
    }
  ]
}```
It would be good to find out if there is a documentation regarding this

**Comment by devlinbd2** [comment]
Currently, the account that creates the Lambda function must be the same account that owns the private image. I will add that as a note in this permissions section.
