### ISSUE TITLE
minor coding error with "Configuring file system access for Lambda functions"

### ISSUE THREAD

**Issue by wgillett** [awsdocs/aws-lambda-developer-guide#291]
In the "Example template.yml towards the bottom of this page:
https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/doc_source/configuration-filesystem.md
there is a mistake. The code says:

      FileSystemConfigs:
      - 
        Arn: !Sub
          - "arn:aws:elasticfilesystem:eu-central-1:123456789101:access-point/fsap-015cxmplb72b405fd"

but the "!Sub" is wrong, there's nothing to substitute. Instead simply do this:

      FileSystemConfigs:
        - Arn: "arn:aws:elasticfilesystem:eu-central-1:123456789101:access-point/fsap-015cxmplb72b405fd"

I copy-pasted the above code into a template which started working when I made this fix.

**Comment by devlinbd2** [comment]
Thank you for submitting the correction to the template. I have corrected the source file. It will be corrected in the GitHub version when we next publish.
