### ISSUE TITLE
The sample-apps/java-basic has an issue with 3-invoke.sh.  It doesn't account for the change made from AWS CLI v1 to v2.

### ISSUE THREAD

**Issue by robinsjm2** [awsdocs/aws-lambda-developer-guide#319]
The sample-apps/java-basic has an issue with 3-invoke.sh.  It doesn't account for the change made from AWS CLI v1 to v2.

https://docs.aws.amazon.com/sdkref/latest/guide/setting-global-cli_binary_format.html#setting-cli_binary_format-detail

To get it to work with AWS CLI v2, the command should be:

`aws lambda invoke --function-name $FUNCTION --cli-binary-format raw-in-base64-out --payload file://event.json out.json`

**Comment by mwunderl** [comment]
Thanks for your feedback. Taking a look at this issue in https://github.com/awsdocs/aws-lambda-developer-guide/issues/180
