### ISSUE TITLE
Contradiction on SQS event source.

### ISSUE THREAD

**Issue by Posnet** [awsdocs/aws-lambda-developer-guide#33]
- https://github.com/awsdocs/aws-lambda-developer-guide/blame/f005f04221ddb043f7f5c8dc5bf4e8e29e3707c5/doc_source/invocation-options.md#L13
- https://github.com/awsdocs/aws-lambda-developer-guide/blame/f005f04221ddb043f7f5c8dc5bf4e8e29e3707c5/doc_source/invoking-lambda-function.md#L109

The first link specifies that the SQS event source is Poll based and is invoked synchronously (like kinesis streams event sources), however the second link says that SQS is async based for the purposes of error handling (like the sns event source). These appear to contradict each other.  
This should ideally be clarified before the SQS event source is launched.

**Comment by jpizarrom** [comment]
Does the SQS support on AWS lambda come soon?
