### ISSUE TITLE
Nodejs Lambda: Cannot find package 'aws-sdk'

### ISSUE THREAD

**Issue by shishkin** [awsdocs/aws-lambda-developer-guide#342]
Reading [the guide](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html), I understand that `aws-sdk` should be already available on Nodejs runtimes. I'm deploying a Nodejs lambda with `@aws-cdk-lib/aws-lambda-nodejs` using NODEJS_14 runtime and I'm getting this error when using an S3 client:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'aws-sdk' imported from /var/task/index.mjs
```

Here is the code of the lambda:

```javascript
// src/lambda.ts
import { S3 } from "aws-sdk";
import { URLSearchParams } from "node:url";
var { REGION, BUCKET_NAME } = process.env;
var s3 = new S3({ region: REGION });
var handler = async (e) => {
  console.debug("Event:", e);
  const { message } = e;
  const greeting = hello(message);
  const s3result = await s3.putObject({
    Bucket: BUCKET_NAME,
    Key: `greetings/hello.txt`,
    Tagging: new URLSearchParams({
      type: "greeting"
    }).toString(),
    ContentType: "text/plain; charset=UTF-8",
    Body: greeting
  }).promise();
  console.debug("S3 result:", s3result);
};
var hello = (message) => `Hello, ${message}!`;
export {
  handler,
  hello
};
```

I've tried both v2 and v3 of JavaScript AWS SDK with same error. What am I missing? I'd like to be able to avoid bundling AWS SDKs into the lambda.

**Comment by augustobritos** [comment]
Hello Shishkin , have you find a solution ? I'm still facing the same issue.

**Comment by shishkin** [comment]
Yes, [this](https://github.com/aws/aws-sdk-js-v3/issues/3230#issuecomment-1046289765) worked for me.

**Comment by augustobritos** [comment]
Oh great @shishkin , thank you so much !

**Comment by mwunderl** [comment]
Apologies for the lack of response. Here are some sample functions that show how to import and use the AWS SDK in Node.js-
https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/blank-nodejs/function/index.js
https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/nodejs-apig/function/index.js
