### ISSUE TITLE
How to restrict custom-built Lambda container base images

### ISSUE THREAD

**Issue by elgalu** [awsdocs/aws-lambda-developer-guide#344]
I'm looking for a Lambda policy solution so that deployed Lambdas must only be allowed to run if the base image used to build them comes from a company internally approved account.

Example where `123456789012` would be the (restricted) company account number:

```json
"Condition": {
    "ForAllValues:StringLike": {
        "lambda:base-image": [
            "123456789012.dkr.ecr.eu-central-1.amazonaws.com/my-approved-images*:*"
        ]
    }
}
```

I couldn't find a way to achieve such restriction, note `lambda:base-image` is something I made up to clarify this request.

**Comment by mwunderl** [comment]
I'll pass this along to the service team. If [code signing](https://docs.aws.amazon.com/lambda/latest/dg/configuration-codesigning.html) worked for containers, would that address your need?
