### ISSUE TITLE
[Documentation] Requirements for building a layer should be in a separate file

### ISSUE THREAD

**Issue by dgard1981** [awsdocs/aws-lambda-developer-guide#350]
I've just added a layer for `aws-xray-sdk` and `jsonpickle` as described in the [README](https://github.com/awsdocs/aws-lambda-developer-guide/tree/main/sample-apps/blank-python#readme) for the blank Python project.

```bash
cd function
pip3 install --target ../package/python -r requirements.txt
```

However, I was finding that the function package still included the required modules as listed in **requirements.txt**. It looks as though that rather than building the layer from **/functoin/requirements.txt** a separate requirements file should be created, and that modules that will be in the layer should be removed from **/functoin/requirements.txt**.

Can the documentation be amended to make this clear, as the existing documentation doesn't seem to acknowledge that at all.

**Comment by mwunderl** [comment]
Hi David, the packages should appear in a `package` folder under `blank-python` and be uploaded separately when you run the deploy script. If you look in your S3 bucket there should be one file for the layer (13MB) and one for the code (3KB). Check your `function` folder to make sure that there aren't any packages in there.
