### ISSUE TITLE
Java basic - custom event WeatherData. function url receive empty Body from postman call

### ISSUE THREAD

**Issue by nghoanganh96** [awsdocs/aws-lambda-developer-guide#370]
i run HandlerWeatherData in java-basic. Used the given event json as
{
  "temperatureK": 281,
  "windKmh": -3,
  "humidityPct": 0.55,
  "pressureHPa": 1020
}
. Invoke successfully once i tested on console lambda function with lambda url (NONE - public access). But when i run on postman the event WeatherData is empty {}
logger.info("EVENT: " + gson.toJson(event)); ==> output: EVENT: {}

**Comment by nghoanganh96** [comment]
i investigated,  Lambda maps the request to an Json as https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html#urls-payloads
So i change request to receive the body

public class WeatherRequest {
    WeatherData body;
    Map<String, String> headers;
// getters, setters
}

But i having another issue: 
An error occurred during JSON parsing: java.lang.RuntimeException
java.lang.RuntimeException: An error occurred during JSON parsing
Caused by: java.io.UncheckedIOException: com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `DAGenerator.model.WeatherData` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('
{
    "temperatureK": 281,
    "windKmh": -3,
    "humidityPct": 0.55,
    "pressureHPa": 1020
}
')

**Comment by nghoanganh96** [comment]
i change WeatherData body -> String body and convert manually String body json to object. it works now

**Comment by sovietspy2** [comment]
Hey!

I came across the this issue. Thanks for the workaround.

But the issue still persist, the example won't work with function URL. If this is intended please state it or update the example.
