### ISSUE TITLE
Lambda Node.js 12 deprecation change of date

### ISSUE THREAD

**Issue by plumdog** [awsdocs/aws-lambda-developer-guide#400]
Originally received correspondence by email on 17th September 2022 from AWS to say:

> Starting November 14, 2022, Lambda will no longer apply security patches and other updates to the Node.js 12 runtime used by Lambda functions, and functions using Node.js 12 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Node.js 12 runtime. Starting December 14, 2022, you will no longer be able to update existing functions using the Node.js 12 runtime.
>
> We recommend that you upgrade your existing Node.js 12 functions to Node.js 16 before November 14, 2022.

But this is not what the docs at https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html say, which now gives the deprecation as Mar 31, 2023.

Have not received any update by email from AWS to say that this date changed.

Via Wayback Machine:
- [On Oct 5th, 2022](https://web.archive.org/web/20221005183709/https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), listed deprecation date as "Nov 14, 2022"
- [On Oct 13th, 2022](https://web.archive.org/web/20221013071341/https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), deprecation date now listed as "Mar 31, 2023"

So between Oct 5th and Oct 13th, the public docs changed to push back the deprecation date by 4 months, but I can find nothing from AWS on the internet announcing it.

(I can't find a matching change in this repo though, as it appears that https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/doc_source/lambda-runtimes.md is well out of date, so I think the docs source is hiding somewhere else.)

Could someone direct me to an something official from AWS that says "we've pushed back Node.js 12 Lambda Runtime deprecation from November 2022 to March 2023"? Something more official than this issue and my digging around with Wayback Machine.

Further, it would really help if when AWS email to say "you need to do this by [date]" that they send another email if that date changes.

**Comment by mwunderl** [comment]
Hi Andrew, thanks for your feedback. I'll pass this on to the service team.
