### ISSUE TITLE
Nodejs handler doc update

### ISSUE THREAD

**Issue by tscully49** [awsdocs/aws-lambda-developer-guide#407]
I noticed the [nodejs handler document](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html) has this sentence for asynchronous handlers. 

`For async handlers, you can use return and throw to send a response or error, respectively. Functions must use the async keyword to use these methods to return a response or error.`

I was wondering if instead of `return` and `throw` the writer meant to say `resolve` and `reject`. The replacement seems to make more sense to me and (I could be wrong) but I think this is what the writer was trying to communicate.

**Comment by alpinisme** [comment]
I think the writer meant code like the following, using the `async` keyword, where `return` and `throw` do result in a resolved or a rejected promise, respectively.
```js
async function handler(event) {
  if (condition) { throw Error('oops') }
  return 'foo'
}
```

**Comment by mwunderl** [comment]
Yes, the idea is that you can return or throw instead of interacting with promises directly.

**Comment by mwunderl** [comment]
Some examples:
https://github.com/awsdocs/aws-lambda-developer-guide/blob/4ab6fc2242df3500769deef8d4378ec6c17d07bd/sample-apps/rds-mysql/dbadmin/index.js#L20
https://github.com/awsdocs/aws-lambda-developer-guide/blob/4ab6fc2242df3500769deef8d4378ec6c17d07bd/sample-apps/nodejs-apig/function/index.js#L12
