### ISSUE TITLE
Max concurrent lambda per SQS queue

### ISSUE THREAD

**Issue by drewpaterson** [awsdocs/aws-lambda-developer-guide#78]
Documentation states "whichever is lower" of 1000, the account limit, or the function limit. This implies that 1000 is the maximum concurrent lambda off of a SQS queue, is this true?

**text from doco https://github.com/awsdocs/aws-lambda-developer-guide/blob/master/doc_source/scaling.md**
As the influx of messages to a queue increases, AWS Lambda automatically scales up polling activity until the number of concurrent function executions reaches 1000, the account concurrency limit, or the (optional) function concurrency limit, whichever is lower. 
**end text**

**Comment by waynerobinson** [comment]
Looks like too much nesting. 🙃

Should probably be in brackets. E.g.

As the influx of messages to a queue increases, AWS Lambda automatically scales up polling activity until the number of concurrent function executions reaches 1000
 (the account concurrency limit) or the (optional) function concurrency limit, whichever is lower.

**Comment by mwunderl** [comment]
Thanks for your feedback. There is a separate limit in this case. I'll update the wording to clarify.

**Comment by mwunderl** [comment]
Updated here-
https://github.com/awsdocs/aws-lambda-developer-guide/blob/master/doc_source/scaling.md

Thanks,
-Michael
