### ISSUE TITLE
AddPermission's SourceArn Parameter Doesn't Specify Supported Event Sources

### ISSUE THREAD

**Issue by joelthompson** [awsdocs/aws-lambda-developer-guide#80]
According to the [CloudFormation AWS::Lambda::Permission docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html#cfn-lambda-permission-sourcearn), "This property [SourceArn] is not supported by all event sources. For more information, see the SourceArn parameter for the AddPermission action in the AWS Lambda Developer Guide." However, SourceArn doesn't specify which even sources are supported.

I could see this being an issue with the CloudFormation docs, but `SourceAccount` does document the supported event sources, so it seems like `SourceArn` should as well.

Thanks!

**Comment by mwunderl** [comment]
Thanks for your feedback. I've updated the description of both CFN and API parameter to give concrete examples, and created a task to standardize permissions content for all event sources. That will include showing use of SourceArn where applicable.
