### ISSUE TITLE
aws-lambda-developer-guide does not mention consumer arn

### ISSUE THREAD

**Issue by toelen** [awsdocs/aws-lambda-developer-guide#94]
AWS Lambda now supports enhanced consumers. When reading https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html#services-kinesis-api I suppose EventSourceArn also understands the consumer arn, but this is not reflected in aws-lambda-developer-guide

**Comment by mwunderl** [comment]
Fixed upon syncing markdown build. Thanks!
